namespace ProjectEuler
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// 
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    public class P002EvenFibonacciNumbers : IProblem
    {
        public int Solve()
        {
            var ultimate = 1;
            var penultimate = 1;
            var sum = 0;
            while (ultimate <= 4000000)
            {
                var newUltimate = ultimate + penultimate;
                penultimate = ultimate;
                ultimate = newUltimate;
                if (ultimate % 2 == 0)
                    sum += ultimate;
            }
            return sum;
        }
    }
}
